[package]
name = "arcus-cli"
version = "1.0.0"
edition = "2024"

[dependencies]
clap = { version = "4.6.4", features = ["derive"] }
rustyline = "18.0.1"
rustyline-derive = "0.12.0"
rsasl = { version = "2.3.1", features = ["provider", "config_builder","scram-sha-2"], default-features = false }
rpassword = "7.5.4"

[features]
with-file-history = []
